on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm ci

      - run: npm test

      - run: npm run coverage

      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.lcov

      - name: Publish on npm
        if: startsWith(github.ref, 'refs/tags/')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
